version: '3'
services:
  mongodb:
    image: mongo
    volumes:
      - ./mongodb/scripts/init:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

  apiservice:
    container_name: BoatApp.Api
    build: 
      context: ./BoatApp.Api
      dockerfile: ./dockerfile.api
    ports: 
      - 5000:80

  uiservice  :
    container_name: BoatApp.ui
    build: 
      context: ./BoatApp.Web
      dockerfile: ./dockerfile.ui
    ports: 
      - 4200:4200